#数据源1
spring:
  datasource:
    source:
      type: com.alibaba.druid.pool.DruidDataSource
      username: dev_user
      password: Yz2bAJWjtAyeTW4dx
      url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=UTC
    target:
      type: com.alibaba.druid.pool.DruidDataSource
      username: dev_user
      password: Yz2bAJWjtAyeTW4dx
      url: jdbc:mysql://127.0.0.1:3306/dev?serverTimezone=UTC
